name: Build Cheat
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b
      
      - name: Prepare jni
        run: |
          mkdir -p jni
          cp cheat.cpp jni/
          cp Android.mk jni/
          cp Application.mk jni/
          echo "=== FILES IN jni ==="
          ls -la jni/
      
      - name: Build
        run: |
          cd jni
          ls -la
          $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk NDK_APPLICATION_MK=Application.mk
          echo "=== FIND .so ==="
          find . -name "*.so"
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: libcheat
          path: jni/libs/arm64-v8a/libcheat.so
          if-no-files-found: error
